### PR TITLE
Wip lesson

### LINKED ISSUE #1: needs content
Refere to [Readme](https://github.com/learn-co-curriculum/sinatra-views-lab) for outline of content 

deadline: 9/17/2015

### PR DESCRIPTION
**Pull request by ipc103**
closes #1 - needs review

@AnnJohn : Estimated time to complete - 25 minutes

### CODE REVIEW

**Comment by AnnJohn** [comment]
Assigned to @dfenjves for review

Deadline: 9/16/15

**Comment by AnnJohn** [comment]
Assigned to @aviflombaum for review

Deadline: 9/16/15

**Comment by aviflombaum** [comment]
Master reviewed, diff https://github.com/learn-co-curriculum/sinatra-views-lab/commit/9166f5cbefe812d327fd28b40c9909bb396feea6

Solution was good, views were missing though so added them.

**Comment by aviflombaum** [comment]
@AnnJohn please mark as Done in spreadsheet.

**Pull request merged**
